version: 2
jobs:
  validate-config:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Validate SWC yaml config schema
          command: |
            cd scripts
            yarn && yarn run schema-validation
  deploy-website:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            git config --global user.name "$GIT_USER"
            echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && npm run content && GIT_USER=$GIT_USER yarn run publish-gh-pages
  updateswc:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Update SWC definition
          command: |
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            git config --global user.name "$GIT_USER"
            echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
            cd scripts && yarn && yarn run updateswc
            cd ../
            command=$(git status|grep swc-definition.json|wc -l)
            if ((command > 0)); then
              git add export/
              git commit -m "Update SWC definition"
              git push -q https://${GIT_TOKEN}@github.com/${GIT_ORGANIZATION}/SWC-registry.git master
            else
              echo "SWC definition already up to date"
              exit 0;
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only: website
              ignore: gh-pages
      - updateswc:
          filters:
            branches:
              only: master
      - validate-config:
          filters:
            branches:
              only: master